name: python V2rayCollector Script

on:
  schedule:
    - cron: '*/60 * * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4

      - name: Run Python script
        run:  python main.py  # Replace with your script's path

      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
           host: smtp.nine.testrun.org
           account: ${{secrets.ACCOUNT}}
           password: ${{secrets.MAIL_PASSWORD}}
           sender: devellany
           from: ${{secrets.MAIL_ADDRESS}}
           to: mwguf6h3w@nine.testrun.org
           subject: mail title.
           body: thks
           contentType: text/html
           attachments: file://sub/region_configs.txt
