name: python V2rayCollector Script

on:
  schedule:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python -m pip install beautifulsoup4

      - name: Run Python script
        run:  python main.py  # Replace with your script's path

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: smtp.nine.testrun.org
           server_port: 465
           username: ${{secrets.ACCOUNT}}
           password: ${{secrets.MAIL_PASSWORD}}
           from: ${{secrets.MAIL_ADDRESS}}
           to: mwguf6h3w@nine.testrun.org
           subject: Github Actions job result.
           body: thks
           attachments: ./sub/region_configs.txt
